---
default_language_version:
  python: python3
exclude: .venv
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0  # or specific git tag
    hooks:
      - id: forbid-binary
        exclude: >
          (?x)^(
            screenshot.png
          )$
      - id: git-check
      - id: script-must-have-extension
      - id: shellcheck
        args: ['--severity=error']

  - repo: https://github.com/ansible/ansible-lint
    rev: v25.12.2
    hooks:
      - id: ansible-lint
        name: Ansible Lint
        language_version: python3
        additional_dependencies:
          - ansible-core
        verbose: false
        # do not pass files to ansible-lint, see:
        # https://github.com/ansible/ansible-lint/issues/611
        pass_filenames: false
        always_run: true

  - repo: https://github.com/robertdebock/pre-commit
    rev: v1.2.2
    hooks:
      - id: ansible_role_find_unused_variable
      - id: ansible_role_find_empty_files
      - id: ansible_role_find_empty_directories
