---
- name: Gather package facts
  ansible.builtin.package_facts:

- name: Ensure package is absent
  when: "'efs' in ansible_facts.packages"
  ansible.builtin.package:
    name: efs
    state: absent
