---
- name: Ubuntu install
  when: "'efs' not in ansible_facts.packages"
  block:
    - name: Find DEB package to install
      ansible.builtin.find:
        paths: "{{ efs_tmp_dir }}"
        patterns: "*.deb"
      register: efs_debian
    - name: Install DEB package
      become: true
      ansible.builtin.apt:
        update_cache: true
        deb: "{{ efs_debian.files[0].path }}"
    - name: Cleanup
      ansible.builtin.file:
        path: "{{ efs_debian.files[0].path }}"
        state: absent
