---
- name: Gather package facts
  ansible.builtin.package_facts:

- name: Check download
  delegate_to: localhost
  connection: local
  run_once: true
  ansible.builtin.stat:
    path: "{{ efs_download_dir }}/{{ efs_installer }}"
  register: efs_download

- name: Download ESET Antivirus
  when: not efs_download.stat.exists
  delegate_to: localhost
  connection: local
  become: false
  run_once: true
  ansible.builtin.get_url:
    url: "{{ efs_url }}"
    dest: "{{ efs_download_dir }}"
    mode: '0755'

- name: Transfer package
  when: "'efs' not in ansible_facts.packages"
  block:
    - name: Copy product bin package
      ansible.builtin.copy:
        src: "{{ efs_download_dir }}/{{ efs_installer }}"
        dest: "{{ efs_tmp_dir }}/{{ efs_installer }}"
        mode: '0700'

    - name: Unpack product bin package
      ansible.builtin.command: "bash {{ efs_tmp_dir }}/{{ efs_installer }} -y -f -n"
      args:
        chdir: "{{ efs_tmp_dir }}"
      changed_when: true

- name: "Configure {{ ansible_os_family }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  tags: always
